/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Button: typeof import('./src/components/Button.vue')['default']
        'Icon:basil:sortOutline': typeof import('~icons/basil/sort-outline')['default']
        'Icon:materialSymbols:arrowBack': typeof import('~icons/material-symbols/arrow-back')['default']
        'Icon:materialSymbols:calendarAddOn': typeof import('~icons/material-symbols/calendar-add-on')['default']
        'Icon:materialSymbols:call': typeof import('~icons/material-symbols/call')['default']
        'Icon:materialSymbols:editCalendar': typeof import('~icons/material-symbols/edit-calendar')['default']
        'Icon:materialSymbols:mailOutline': typeof import('~icons/material-symbols/mail-outline')['default']
        'Icon:materialSymbols:notes': typeof import('~icons/material-symbols/notes')['default']
        'Icon:mdi:contentSave': typeof import('~icons/mdi/content-save')['default']
        'Icon:typcn:userAddOutline': typeof import('~icons/typcn/user-add-outline')['default']
        'IconMaterialSymbols:arrowBack': typeof import('~icons/material-symbols/arrow-back')['default']
        'IconMdi:contentSave': typeof import('~icons/mdi/content-save')['default']
        'IconMdi:houseAddOutline': typeof import('~icons/mdi/house-add-outline')['default']
        Input: typeof import('./src/components/Input.vue')['default']
        InteressentListItem: typeof import('./src/components/InteressentListItem.vue')['default']
        PropertyListItem: typeof import('./src/components/PropertyListItem.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SearchBar: typeof import('./src/components/SearchBar.vue')['default']
        Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    }
}
